// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240719141509_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "أدوات ومعدات",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "سيارات ومركبات",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "الإلكترونيات",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "أجهزة إلكترونية",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "المطبخ والمنزل",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "معدات البستنة",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "أدوات رياضية",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "أدوات الحيوانات الأليفة",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "الفنون والحرف",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "السفر والأمتعة",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "الكرفانات",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "الآلات الموسيقية",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 13,
                            CategoryName = "الحفلات والمناسبات",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 14,
                            CategoryName = "الملابس والبدلات",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 15,
                            CategoryName = "المعدات الطبية",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 16,
                            CategoryName = "ألعاب الطاولة والألغاز",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 17,
                            CategoryName = "مستلزمات التعلم",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 18,
                            CategoryName = "الألعاب الإلكترونية",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 19,
                            CategoryName = "المركبات المائية",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 20,
                            CategoryName = "أثاث المنزل",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 21,
                            CategoryName = "مستلزمات المكتب",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 22,
                            CategoryName = "معدات البناء",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 23,
                            CategoryName = "معدات الصيد",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 24,
                            CategoryName = "مستلزمات التخييم",
                            CategoryType = "product"
                        },
                        new
                        {
                            Id = 25,
                            CategoryName = "مستلزمات الخياطة",
                            CategoryType = "product"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
